@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjI1MmQzNTgzYTY0Y2M2MTk4MmI4ZmEiLCJmaXJzdE5hbWUiOiJhIiwibGFzdE5hbWUiOiJiIiwiZW1haWwiOiJhYkBlbWFpbC5jb20iLCJpYXQiOjE3MTM4ODU3NzZ9.nOTAqJPTa8QuGtv_upfcDnx5YQNqezX5eGfInoPddrw

POST http://localhost:3000/users/signup
#Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "name": {
        "first": "a",
        "last": "b"
    },
    "email": "ab2@email.com",
    "phone": "+1123445",
    "password": "abcd"
}

### Test POST request for signing in
POST http://localhost:3000/users/signin
Content-Type: application/json

{
    "email": "ab@email.com",
    "password": "abcd"
}