export enum EVENT_STATUS {
    SCHEDULED = 'SCHEDULED',
    CANCELLED = 'CANCELLED',
    ENDED = 'ENDED',
    ONGOING = 'ONGOING'
};

export enum EVENT_TEAM_RESULT {
    WON = 'WON',
    LOST = 'LOST',
    CONCEDED = 'CONCEDED',
    UNDECIDED = 'UNDECIDED'
};